### PR TITLE
Request processing timeout

### PR DESCRIPTION
**Pull request by dionisiydk**
- Network can be configured with #requestProcessingTimeout
- The default value is defined on class side as #defaultRequestProcessingTimeout (nil by default)

Internally SeamlessSynchRequestContext was refactored: SeamlessRequestResultDelivery was extracted with semaphore synchronization logic. For timeout behavior special subclass of delivery was implemented,  SeamlessRequestResultTimelyDelivery

### CODE REVIEW

**Comment by dionisiydk** [comment]
see #39

**Comment by dionisiydk** [comment]
@oliveiraallex  I will add real setting later. Basically some pragma method is needed on the network class. But I need to check if we have something to specify duration (timeout is not a raw number)

**Comment by dionisiydk** [comment]
@oliveiraallex do we need this setting? You can set up timeout with following script:
```Smalltalk
SeamlessNetwork defaultRequestProcessingTimeout: 1 second
```

**Comment by oliveiraallex** [comment]
Hi @dionisiydk thank you very much! 

> @oliveiraallex do we need this setting? You can set up timeout with following script:
> 
> ```smalltalk
> SeamlessNetwork defaultRequestProcessingTimeout: 1 second
> ```

Yes, the settings it's not necessary, but I think when we have settings that we can just go there and click on it or fill a box with a parameter, it's easier to use. I'm thinking also in do settings to telepharo, like disable slow plugins, etc. Sometimes we need to search for how to do that and lost some time. 

I saw this method #defaultRequestProcessingTimeout: and #requestProcessingTimeout: but it has been used only in the test? Is it not implemented yet? 

I saw in SeamlessNetwork #initialize the connectionTimeout := 10 seconds. What is this and why it's hardcoded? I didn't understand, because I tested when I lost the connection, this timeout doesn't do anything. Maybe it's for some other thing than connectionTimeout.

**Comment by dionisiydk** [comment]
> I saw this method #defaultRequestProcessingTimeout: and #requestProcessingTimeout: but it has been used only in the test? Is it not implemented yet?

They are accessors. Users can setup specific value per network instance or change global default value:
```Smalltalk
SeamlessNetwork defaultRequestProcessingTimeout: 10 seconds.
network := SeamlessNetwork new.
self assert: network requestProcessingTimeout equals: 10 seconds.

network requestProcessingTimeout: 2 seconds.
self assert: network requestProcessingTimeout equals: 2 seconds.

network2 := SeamlessNetwork new.
self assert: network2 requestProcessingTimeout equals: 10 seconds.
```

> 
> I saw in SeamlessNetwork #initialize the connectionTimeout := 10 seconds. What is this and why it's hardcoded? I didn't understand, because I tested when I lost the connection, this timeout doesn't do anything. Maybe it's for some other thing than connectionTimeout.

It's defined in Basys layer. Check BasysNetwork>>#establishNewConnectionTo:. It is a timeout for socket connection.
The hardcoded value is default one but you can configure network instance to have specific one:
```
network connectionTimeout: 1 minutes
```
I will make it to be same like processingTimeout with default constant method on class side.

**Comment by oliveiraallex** [comment]
It was nice the new implementation, but still not working the timeout in this way. The error changes the place, now it's freezing in SeamlessRequestResultDelivery #waitResult.

When I lost the connection, the Pharo freeze, like before.

**Comment by oliveiraallex** [comment]
I added this timeout in this method, it's avoiding to freeze Pharo now. But I don't know if this is the correct place, because continuous like an error and not nice behavior. 

*is it ok do I push in your PR? Because I realized you never push any code in my PRs...

**Comment by dionisiydk** [comment]
> I added this timeout in this method, it's avoiding to freeze Pharo now. But I don't know if this is the correct place, because continuous like an error and not nice behavior.
> 
> *is it ok do I push in your PR? Because I realized you never push any code in my PRs...

It's better to discuss it first because I think you did not understand the code.
There is now two kind of deliveries. Default one (SeamlessRequestResultDelivery) is working without timeout and waits forever. And there is timely delivery (SeamlessRequestResultTimelyDelivery) configured with timeout.

I think the issue is that the default timeout does not affect existing instances of the network and that is why you did not see new class taking place. Is it sounds familiar?

I will change the implementation to not hold the default value in the variable and use lazy accessor instead. So if user does not configure special timeout for network the default will be used whatever value it has in any given time

**Comment by dionisiydk** [comment]
> is it ok do I push in your PR? Because I realized you never push any code in my PRs...

because in past it was not working from Iceberg and I lazy to go to git

**Comment by oliveiraallex** [comment]
>> It's better to discuss it first because I think you did not understand the code.
> There is now two kind of deliveries. Default one (SeamlessRequestResultDelivery) is working without timeout and waits forever. And there is timely delivery (SeamlessRequestResultTimelyDelivery) configured with timeout.
> 
> I think the issue is that the default timeout does not affect existing instances of the network and that is why you did not see new class taking place. Is it sounds familiar?
> 
> I will change the implementation to not hold the default value in the variable and use lazy accessor instead. So if user does not configure special timeout for network the default will be used whatever value it has in any given time

Yes, I'm trying to understand it better, sorry. Yes, I realized there are two kinds of deliveries, I will debug it more to understand better.

**Pull request merged**
